[pytest]
# -s: Hiển thị print/log ra terminal ngay khi đang chạy
# -v: Chế độ hiển thị chi tiết (Verbose)
addopts = -s -v --alluredir=allure-results
testpaths = tests
# DÒNG QUAN TRỌNG: Fix lỗi ModuleNotFoundError
pythonpath = .